require 'simplecov'
SimpleCov.start
require 'time'
require 'Minitest/autorun'
require 'Minitest/pride'
require 'pry'
require 'mocha/minitest'
require './lib/crypt'
require './lib/decrypt'
require './lib/encrypt'
require './lib/enigma'
require './lib/enigmatic'
require './lib/shift'
require './lib/shiftable'
